Associados/Associados.Web/Controllers/AssociadoesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Associados.Core;
using Associados.Data;

namespace Associados.Web.Controllers
{
    public class AssociadoesController : Controller
    {
        private AssociadoRepository db = new AssociadoRepository();

        // GET: Associadoes
        public ActionResult Index()
        {
            return View(db.List());
        }

        // GET: Associadoes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Associado associado = db.findById(Convert.ToInt32(id));
            if (associado == null)
            {
                return HttpNotFound();
            }
            return View(associado);
        }

        // GET: Associadoes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Associadoes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Nome,Apelido,Email")] Associado associado)
        {
            if (ModelState.IsValid)
            {
                db.Add(associado);
                return RedirectToAction("Index");
            }

            return View(associado);
        }

        // GET: Associadoes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Associado associado = db.findById(Convert.ToInt32(id));
            if (associado == null)
            {
                return HttpNotFound();
            }
            return View(associado);
        }

        // POST: Associadoes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Nome,Apelido,Email")] Associado associado)
        {
            if (ModelState.IsValid)
            {
                db.Edit(associado);
                return RedirectToAction("Index");
            }
            return View(associado);
        }

        // GET: Associadoes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Associado associado = db.findById(Convert.ToInt32(id));
            if (associado == null)
            {
                return HttpNotFound();
            }
            return View(associado);
        }

        // POST: Associadoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            db.Remove(id);
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                //db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Associados/Associados.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
        @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarsExampleDefault">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    @Html.ActionLink("Home", "Index", "Home", null, new { @class = "nav-link" })
                </li>
                <li class="nav-item">
                    @Html.ActionLink("Associados", "Index", "Associadoes", null, new { @class = "nav-link" })
                </li>
                <li class="nav-item">
                    @Html.ActionLink("Moradas", "Index", "Moradas", null, new { @class = "nav-link" })
                </li>
                <li class="nav-item">
                    @Html.ActionLink("Quotas", "Index", "Quotas", null, new { @class = "nav-link" })
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown</a>
                    <div class="dropdown-menu" aria-labelledby="dropdown01">
                        <a class="dropdown-item" href="#">Action</a>
                        <a class="dropdown-item" href="#">Another action</a>
                        <a class="dropdown-item" href="#">Something else here</a>
                    </div>
                </li>
            </ul>
            <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
                <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css">
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            var oTable = $("table#myDataTables").DataTable({
                "ajax": {
                    "url": "Moradas/GetMoradas",
                    "type": "GET",
                    "dataType": "json"
                },
                "columns": [
                    { "data": "TipoVia", "title": "Código", "autowidth": true },
                    { "data": "NomeVia", "title": "Nome", "autowidth": true },
                    { "data": "Porta", "title": "Email", "autowidth": true },
                    { "data": "Andar", "title": "Telefone", "autowidth": true },
                    { "data": "CodigoPostal", "title": "Estado", "autowidth": true },
                ]
            });
        })
    </script>
</body>
</html>